version: "3.9"

services:
  rabbit:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Yönetim paneli (http://localhost:15672)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 20

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: sis_student
      POSTGRES_USER: sis
      POSTGRES_PASSWORD: sis
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sis -d sis_student"]
      interval: 5s
      timeout: 3s
      retries: 20

  student-service:
    build:
      context: ../..
      dockerfile: student-service/Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sis_student
      SPRING_DATASOURCE_USERNAME: sis
      SPRING_DATASOURCE_PASSWORD: sis

      # >>> RABBITMQ bağlantısı
      SPRING_RABBITMQ_HOST: rabbit
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    ports:
      - "8081:8081"
    depends_on:
      rabbit:
        condition: service_healthy
      db:
        condition: service_healthy
