server:
  port: 8081

error:
  include-message: always
  include-binding-errors: always
  include-stacktrace: ALWAYS


spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/sis_student
    username: student
    password: student
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate   # Şemayı Flyway yönetir
    open-in-view: false
    properties:
      hibernate.format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: "never"

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.amqp: info
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG