spring:
  test:
    database:
      replace: none   # Embedded DB’ye zorlamayı kapat
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate   # Şemayı Flyway yönetecek
  flyway:
    enabled: true
    locations: classpath:db/migration
    clean-disabled: false

logging:
  level:
    org.testcontainers: INFO
